SET @hour := -1; # 변수 선언시 ; 잊지 말기

SELECT (@hour:=@hour+1) AS 'HOUR', 
       # (SELECT COUNT(NAME) FROM ANIMAL_OUTS WHERE HOUR(DATETIME) = @hour) AS 'COUNT'
       (SELECT COUNT(HOUR(DATETIME)) 
    FROM ANIMAL_OUTS 
    WHERE HOUR(DATETIME)=@HOUR) AS COUNT 
FROM ANIMAL_OUTS
WHERE @hour < 23
