SELECT CATEGORY, PRICE AS 'MAX_PRICE', PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE PRICE IN (
    SELECT MAX(PRICE) 
    FROM FOOD_PRODUCT  
    GROUP BY CATEGORY
)
AND CATEGORY IN ('과자','국','김치','식용유')
ORDER BY PRICE DESC

# 서브 쿼리가 필요한 이유(SELECT 절에서 단순히 MAX(PRICE) AS MAX_PRICE 하면 안되는 이유):
# PRODUCT_NAME은 CATEGORY로 그룹화할 때, MAX_PRICE에 알맞은 PRODUCT_NAME을 조회해 주는 것이 아니라 
# CATEGORY로 그룹화할 때 테이블의 상단에 있는 데이터를 가져온다!!!!